name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/goreleaser/goreleaser-cross:v1.25.7
    steps:
      - name: Install git-lfs
        run: apt-get update && apt-get install -y git-lfs

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Fetch tags
        run: |
          git config --global --add safe.directory /__w/engram/engram
          git fetch --force --tags

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: "ui/package-lock.json"

      - name: Install cosign
        uses: sigstore/cosign-installer@v3

      - name: Run GoReleaser
        run: goreleaser release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

